Repository nanalmoa/nanalmoa, pull requests merged in 2024-12, with the labels that each got.

#23 [BE] 종일 일정 시간대 버그
  packages/server/src/modules/schedules/schedules.service.ts
Labels: 버그픽스

#26 [FE/BE] husky, lint-staged 설정
  .husky/pre-commit
  package.json
  packages/client/.husky/pre-commit
  packages/client/package.json
  yarn.lock
Labels: 환경설정

#33 [FE] 이미지 엑박 버그 픽스
  package.json
  packages/client/src/assets/imgs/calendar.png
  packages/client/src/assets/imgs/camera.png
  packages/client/src/assets/imgs/error.png
  packages/client/src/assets/imgs/event.png
  packages/client/src/assets/imgs/kakao-login.png
  packages/client/src/assets/imgs/kakaoLogin.png
  packages/client/src/assets/imgs/microphone.png
  packages/client/src/assets/imgs/naver-login.png
  packages/client/src/assets/imgs/naverLogin.png
  packages/client/src/assets/imgs/success.png
  packages/client/src/assets/logo/landingLogo.svg
  packages/client/src/assets/logo/logo.svg
  packages/client/src/assets/svgs/landing-logo.svg
  packages/client/src/assets/svgs/logo.svg
  packages/client/src/components/layout/Header.tsx
  packages/client/src/pages/LandingPage.tsx
  packages/client/src/pages/LoginPage.tsx
  packages/client/tsconfig.app.json
Labels: 버그픽스

#32 [FE] 일정 생성 폼 리팩토링
  packages/client/src/components/common/schedule-form/ScheduleForm.tsx
  packages/client/src/components/common/schedule-form/field-components/BaseField.tsx
  packages/client/src/components/common/schedule-form/field-components/BaseSection.tsx
  packages/client/src/components/common/schedule-form/field-components/CategoryField.tsx
  packages/client/src/components/common/schedule-form/field-components/DateTimeField.tsx
  packages/client/src/components/common/schedule-form/field-components/GroupField.tsx
  packages/client/src/components/common/schedule-form/field-components/RepetitionField.tsx
  packages/client/src/components/common/schedule-form/field-components/TextAreaField.tsx
  packages/client/src/components/common/schedule-form/field-components/TextInputField.tsx
  packages/client/src/components/common/schedule-form/field-components/ToggleField.tsx
  packages/client/src/types/category.ts
  packages/client/src/types/schedules.ts
Labels: 버그픽스, 리팩토링

#39 hotfix: 파일명에 앞에 붙는 맥 운영체제의 특수문자제거
  packages/client/src/test/sum.test.ts
Labels: 버그픽스

#41 [BE] 커스텀 데코레이터 구현, 트랜잭션 적용
  .gitignore
  packages/client/src/assets/imgs/calendar.png
  packages/client/src/assets/imgs/camera.png
  packages/client/src/assets/imgs/error.png
  packages/client/src/assets/imgs/event.png
  packages/client/src/assets/imgs/kakao-login.png
  packages/client/src/assets/imgs/microphone.png
  packages/client/src/assets/imgs/naver-login.png
  packages/client/src/assets/imgs/success.png
  packages/client/src/assets/svgs/landing-logo.svg
  packages/client/src/assets/svgs/logo.svg
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/common/decorators/get-user-uuid.decorator.ts
  packages/server/src/dataSource.ts
  packages/server/src/entities/recurring-schedule.entity.ts
  packages/server/src/entities/schedule.entity.ts
  packages/server/src/main.ts
  packages/server/src/modules/group/group.controller.ts
  packages/server/src/modules/group/group.service.ts
  packages/server/src/modules/invitations/invitations.controller.ts
  packages/server/src/modules/manager/manager.controller.ts
  packages/server/src/modules/schedules/OCR-transcription.service.ts
  packages/server/src/modules/schedules/dto/create-schedule.dto.ts
  packages/server/src/modules/schedules/dto/response-schedule.dto.ts
  packages/server/src/modules/schedules/dto/update-schedule.dto.ts
  packages/server/src/modules/schedules/schedules.controller.ts
  packages/server/src/modules/schedules/schedules.module.ts
  packages/server/src/modules/schedules/schedules.service.ts
  packages/server/src/modules/users/users-routine.controller.ts
  packages/server/src/modules/users/users.controller.ts
  packages/server/swagger.json
  yarn.lock
Labels: 리팩토링

#47 [HOTFIX] 이미지 파일 삭제 오류
  .gitattributes
  packages/client/src/assets/imgs/calendar.png
  packages/client/src/assets/imgs/camera.png
  packages/client/src/assets/imgs/error.png
  packages/client/src/assets/imgs/event.png
  packages/client/src/assets/imgs/microphone.png
  packages/client/src/assets/imgs/success.png
  packages/server/src/entities/user-group.entity.ts
  packages/server/src/entities/user.entity.ts
Labels: 버그픽스

#48 [BE] 엔티티 fk 일관성 설정
  packages/server/src/entities/manager-invitation.entity.ts
  packages/server/src/entities/manager-subordinate.entity.ts
  packages/server/src/entities/user.entity.ts
  packages/server/src/modules/manager/manager.service.ts
Labels: 리팩토링

#52 [BE] AI 및 GPT 처리 로직 서비스 분리
  packages/server/src/modules/schedules/OCR-transcription.service.ts
  packages/server/src/modules/schedules/ai.service.ts
  packages/server/src/modules/schedules/schedules.controller.ts
  packages/server/src/modules/schedules/schedules.module.ts
  packages/server/src/modules/schedules/schedules.service.ts
Labels: 리팩토링

#56 [BE] 일정 업데이트 및 삭제 관련 서비스 코드 분리
  packages/server/src/modules/schedules/ai.service.ts
  packages/server/src/modules/schedules/recurring-schedules.service.ts
  packages/server/src/modules/schedules/schedules.module.ts
  packages/server/src/modules/schedules/schedules.service.ts
  packages/server/src/modules/schedules/schedules.util.ts
  packages/server/src/modules/schedules/voice-transcription.service.ts
Labels: 리팩토링

#58 [BE] 스케쥴 서비스(생성, 조회), 컨트롤러 리팩토링
  package-lock.json
  packages/server/package.json
  packages/server/src/modules/schedules/dto/create-schedule.dto.ts
  packages/server/src/modules/schedules/group-schedules.service.ts
  packages/server/src/modules/schedules/recurring-schedules.service.ts
  packages/server/src/modules/schedules/schedules.controller.ts
  packages/server/src/modules/schedules/schedules.docs.ts
  packages/server/src/modules/schedules/schedules.module.ts
  packages/server/src/modules/schedules/schedules.service.ts
  packages/server/src/modules/schedules/schedules.util.ts
  packages/server/src/modules/schedules/types/date-range-params.interface.ts
  packages/server/src/modules/schedules/types/date-range.interface.ts
  packages/server/src/modules/schedules/types/period.enum.ts
  packages/server/src/modules/users/users.service.ts
  packages/server/swagger.json
  yarn.lock
Labels: 리팩토링
