Repository nanalmoa/nanalmoa, pull requests merged in 2025-03, with the labels that each got.

#72 [FE] 일정폼 그룹 기능 연결
  packages/client/src/components/common/schedule-form/ScheduleForm.tsx
  packages/client/src/components/common/schedule-form/field-components/GroupField.tsx
  packages/client/src/pages/ScheduleDetailPage.tsx
  packages/client/src/types/schedules.ts
Labels: 기능추가

#74 [FE] 일정폼 반복 기능 추가
  packages/client/src/components/common/schedule-form/ScheduleForm.tsx
  packages/client/src/components/common/schedule-form/field-components/RepetitionField.tsx
  packages/client/src/components/common/schedule-form/field-components/RepititionSetModal.tsx
  packages/client/src/pages/ScheduleDetailPage.tsx
  packages/client/src/pages/create-schedule/CreateManualSchedulePage.tsx
  packages/client/src/types/schedules.ts
Labels: 기능추가

#76 [FE] 에러 처리 파일 획일화
  packages/server/src/common/exception/business.exception.ts
  packages/server/src/common/exception/error-codes.enum.ts
  packages/server/src/common/exception/error-response.dto.ts
  packages/server/src/common/exception/global-exception.filter.ts
  packages/server/src/modules/schedules/schedules.service.ts
Labels: 기능추가, 리팩토링

#78 [BE] 에러 코드 수정
  package-lock.json
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/strategies/naver.strategy.ts
  packages/server/src/modules/group/group.service.ts
  packages/server/src/modules/invitation/invitations.service.ts
  packages/server/src/modules/invitations/invitations.controller.ts
  packages/server/src/modules/invitations/invitations.service.ts
  packages/server/src/modules/manager/manager.service.ts
  packages/server/src/modules/schedules/ai.service.ts
  packages/server/src/modules/schedules/recurring-schedules.service.ts
  packages/server/src/modules/schedules/schedules.controller.ts
  packages/server/src/modules/schedules/schedules.service.ts
  packages/server/src/modules/users/users-routine.controller.ts
  packages/server/src/modules/users/users-routine.service.ts
  packages/server/src/modules/users/users.controller.ts
  packages/server/src/modules/users/users.service.ts
  packages/server/swagger.json
  yarn.lock
Labels: 리팩토링

#80 [CHORE] 워크 플로우 수정
  .github/workflows/ci.yml
Labels: 환경설정

#81 [FIX] 워크 플로우에 환경변수 추가
  .github/workflows/ci.yml
  .github/workflows/client-cd.yml
  .github/workflows/server-cd.yml
Labels: 환경설정
